database_file: "/home/moritz/Biocondensates/predictor/lammps_input_generator_for_mpipi/rg_workflow/samples.parquet"
lammps_binary: "/home/moritz/Biocondensates/lammps/bin/lmp"

temperature: 10
ionic_strength: 150
n_steps: 50000000
timestep: 10.0
minimum_domain_length: 3
minimum_idr_length: 3

rg_skip: 20

accessions : ["P37840"]
thresholds: [50.0, 60.0, 70.0, 80.0, 90.0]

# MareNostrum
marenostrum_compute:
  gp_debug:
    queue_name: gp_debug
    maximum_time_limit: 02:00:00
    number_of_cores: 112 # Max. seems to be 112 per node
    nodes: 1
  gp_resa:
    queue_name: gp_resa
    maximum_time_limit: 3-00:00:00
    number_of_cores: 112 # Max. seems to be 112 per node
    nodes: 1
